export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_SELECTED_PROCUTDETAILS_PENDING = "FETCH_SELECTED_PROCUTDETAILS_PENDING";
export const FETCH_SELECTED_PROCUTDETAILS_SUCCESS = "FETCH_SELECTED_PROCUTDETAILS_SUCCESS";
export const FETCH_SELECTED_PROCUTDETAILS_ERROR = "FETCH_SELECTED_PROCUTDETAILS_ERROR";
